version: '3.8'
services:
  db:
    image: mysql:8.0.33
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=yulkost
      - MYSQL_ROOT_PASSWORD=19804731205
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - '8081:8081'
volumes:
  db:
    driver: local