version: '3.8'
services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=yulkost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=19804731205
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - db
volumes:
  db:
    driver: local
