version: '3.8'
services:
  db:
    image: mysql:8.0.33
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=yulkost
      - MYSQL_ROOT_PASSWORD=19804731205
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - db
volumes:
  db:
    driver: local
