spring:
  database:
    url: mysql.railway.internal
    name: railway
    username: root
    password: sKXxriCmfiRXgcYxBEYxOeKzaoticKbh
  flyway:
    locations: classpath:migrations
    url: jdbc:mysql://${spring.database.url}/${spring.database.name}
    user: ${spring.database.username}
    password: ${spring.database.password}
  datasource:
    url: jdbc:mysql://${spring.database.url}/${spring.database.name}
    user: ${spring.database.username}
    password: ${spring.database.password}
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080
  servlet:
    session:
      timeout: 14h
