spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:mysql://192.168.1.100:3306/yulkost
    user: kostya
    password: 19804731205
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/yulkost
    username: kostya
    password: 19804731205
  jpa:
    hibernate:
      ddl-auto: validate
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    session:
      timeout: 14h
