spring:
   flyway:
     locations: classpath:migrations
     url: jdbc:postgresql://host.docker.internal:5432/yulkost
     user: root
     password: 19804731205
   datasource:
     url: jdbc:postgresql://host.docker.internal:5432/yulkost
     username: root
     password: 19804731205
   jpa:
     hibernate:
       ddl-auto: validate
server:
   address: 0.0.0.0
   port: 8081
   servlet:
     session:
       timeout: 14h
