spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    locations: classpath:migrations
    url: jdbc:mysql://localhost:3306/yulkost
    user: kostya
    password: 19804731205
    baselineOnMigrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/yulkost
    username: kostya
    password: 19804731205
  jpa:
    hibernate:
      ddl-auto: update
server:
  address: 0.0.0.0
  port: 8081
